app = "vakhta-bot"
primary_region = "arn"

[build]
  image = "flyio/flyctl:latest"

[env]
  BOT_TOKEN = "8315566098:AAEIVhFSbWLkvdRsdRaWrrzwzU_hBlf8X64"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # ⬅️ ВАЖНО! Отключаем автостоп
  auto_start_machines = true
  min_machines_running = 1    # ⬅️ ВАЖНО! Минимум 1 машина

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  path = "/"
  timeout = "2s"
